apiVersion: v1
kind: Pod
metadata:
  name: busybox
  
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "50m"
        memory: 50Mi
      requests:
        cpu: "50m"
        memory: 50Mi 
  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  
  labels:
    app: app-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      name: app-server
       

      labels:
        app: app-server
    spec:
      containers:
      - name: app-server       
        image: 805199394057.dkr.ecr.us-east-2.amazonaws.com/mbora/goserver:latest
        imagePullPolicy: Always
        env: 
          - name: MONITOR_RATE_SEC
            value: "5"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  
spec:
  selector:
    app: app-server
  ports:
    - name: svc
      port: 9090
      protocol: TCP
      targetPort: 3000  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  
  labels:
    app: db-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-server
  template:
    metadata:
      name: db-server
  

      labels:
        app: db-server
    spec:
      containers:
      - name: db-server        
        image: 805199394057.dkr.ecr.us-east-2.amazonaws.com/mbora/goserver:latest
        imagePullPolicy: Always
        env: 
          - name: MONITOR_RATE_SEC
            value: "5"
      
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  selector:
    app: db-server
  ports:
    - name: svc
      port: 9090
      protocol: TCP
      targetPort: 3000  
---
